### ISSUE TITLE
#TODO before first big release

### ISSUE THREAD

**Issue by BlaQPhoeniX** [BlaQPhoeniX/cwcraftsbot#9]
- [ ] PonyORM migrations
- [ ] data import/export
- [ ] user profile extensions for stock/access level
- [ ] recipe builder for privileged user
- [ ] buy/learn/craft inline buttons
- [ ] prettify recipe tree
